Feat/test block generator
CleverCloud/terraform-provider-clevercloud pull request #64
Opened 2024-04-04 13:11 UTC by TheCrabe

Closes #59

2024-04-05 08:36 UTC, miton18 requested changes

2024-04-05 08:36 UTC, miton18 commented on pkg/helper/provider_block.go
> +func NewProvider(provider string, opts ...ProviderOption) *Provider {
```suggestion
func NewProvider(providerName string, opts ...ProviderOption) *Provider {
```

2024-04-05 08:36 UTC, miton18 commented on pkg/helper/provider_block.go
> +	Provider     string
fields can be private

2024-04-05 08:36 UTC, miton18 commented on pkg/helper/provider_block_test.go
> +		// TODO: Add test cases.
useless

2024-04-05 08:36 UTC, miton18 commented on pkg/helper/ressource_block.go
> +func NewRessource(ressource string, opts ...RessourceOption) *Ressource {
```suggestion
func NewRessource(ressourceName string, opts ...RessourceOption) *Ressource {
```

2024-04-05 08:36 UTC, miton18 commented on pkg/helper/ressource_block.go
> +	Ressource    string
fields can be private

2024-04-05 08:36 UTC, miton18 commented on pkg/helper/ressource_block.go
> +func NewRessource(ressource string, opts ...RessourceOption) *Ressource {
In the prototype, you must accept all required parameters, 
for a provider, we have the providerName, but for a resource, we have it's kind and it's name

2024-04-05 08:36 UTC, miton18 commented on pkg/helper/ressource_block.go
> +	if len(p.StringValues) != 0 {
do you really need this check ?

2024-04-05 08:36 UTC, miton18 commented on pkg/helper/ressource_block.go
> +	if len(p.IntValues) != 0 {
do you really need this check ?

2024-04-05 08:36 UTC, miton18 commented on pkg/helper/ressource_block_test.go
> +		// TODO: Add test cases.
useless

2024-04-05 08:36 UTC, miton18 commented on pkg/helper/ressource_block.go
> +		for _, k := range tmp {
Do you want to try https://github.com/CleverCloud/terraform-provider-clevercloud/blob/master/pkg/map.go#L49 ?

2024-04-05 08:36 UTC, miton18 commented on pkg/helper/ressource_block.go
> +		for _, k := range tmp {
Do you want to try https://github.com/CleverCloud/terraform-provider-clevercloud/blob/master/pkg/map.go#L49 ?

2024-04-05 08:36 UTC, miton18 commented on pkg/resources/python/resource_python_test.go
> -//go:embed provider_test_block.tf
You can also remove the corresponding file

2024-04-05 08:36 UTC, miton18 commented on pkg/resources/python/resource_python_test.go
> +			Config:       helper.NewProvider("clevercloud").SetOrganisation(org).String() + fmt.Sprintf(pythonBlock, rName, rName),
You can also use your Resource helper to replace 
`fmt.Sprintf(pythonBlock, rName, rName)`

2024-04-05 09:09 UTC, TheCrabe commented on pkg/helper/provider_block.go
> +func NewProvider(provider string, opts ...ProviderOption) *Provider {
done

2024-04-05 12:24 UTC, TheCrabe commented on pkg/helper/ressource_block.go
> +	if len(p.StringValues) != 0 {
I do it to skip all steps that are in it but mostly to avoid adding an empty string to s
Otherwise I can make s another way

2024-04-05 12:25 UTC, TheCrabe commented on pkg/helper/ressource_block.go
> +	if len(p.IntValues) != 0 {
Same as the stringValue check but I can also make it differently

(edit: stringValues and intValues have default values so never empty !)

2024-04-17 13:28 UTC, miton18 approved these changes

2024-04-17 13:37 UTC, merged